SET PARTNER_NAME = '<Partner Name>';
SET DATABASE_NAME = $PARTNER_NAME || '_DB';
SET SCHEMA_NAME = $DATABASE_NAME || '.PUBLIC';
SET WAREHOUSE_NAME = $PARTNER_NAME || '_WH';
SET WAREHOUSE_SIZE = '<warehouse_size>';
SET ROLE_NAME = $PARTNER_NAME || '_RL';
SET USER_NAME = $PARTNER_NAME || '_USER';