SET PARTNER_NAME = '<Partner Name>';
SET DATABASE_NAME = $PARTNER_NAME || '_DB';
SET SCHEMA_NAME = $DATABASE_NAME || '.PUBLIC';
SET WAREHOUSE_NAME = $PARTNER_NAME || '_WH';
SET WAREHOUSE_SIZE = '<Warehouse Size#"XS","S", "Medium","Large","X-Large", "2X-Large","3X-Large","4X-Large">';
SET ROLE_NAME = $PARTNER_NAME || '_RL';
SET USER_NAME = $PARTNER_NAME || '_USER';
SET ANYVAR = '<A Variable>';
SET ANYOTHERVAR = '<Another Variable>';

USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS IDENTIFIER($DATABASE_NAME);

CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($WAREHOUSE_NAME)
WITH WAREHOUSE_SIZE = $WAREHOUSE_SIZE
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_NAME)

GRANT ALL
ON WAREHOUSE IDENTIFIER($WAREHOUSE_NAME)
TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE
ON DATABASE IDENTIFIER($DATABASE_NAME)
TO ROLE IDENTIFIER($ROLE_NAME);
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE PIPE, CREATE PROCEDURE, CREATE FUNCTION, MODIFY, USAGE
ON ALL SCHEMAS IN DATABASE IDENTIFIER($DATABASE_NAME)
TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE
ON FUTURE SCHEMAS IN DATABASE IDENTIFIER($DATABASE_NAME)
TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT
ON FUTURE TABLES IN SCHEMA IDENTIFIER($SCHEMA_NAME)
TO ROLE IDENTIFIER($ROLE_NAME);
GRANT SELECT
ON FUTURE VIEWS IN SCHEMA IDENTIFIER($SCHEMA_NAME)
TO ROLE IDENTIFIER($ROLE_NAME);

CREATE USER IF NOT EXISTS IDENTIFIER($USER_NAME) password='<password>';
GRANT ROLE IDENTIFIER($ROLE_NAME) TO USER IDENTIFIER($USER_NAME);